// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7PVOK3GWMdNide3ef8mNTcDX0MAIO1Q',
    appId: '1:379614277244:web:888d75a55dc024faed23f9',
    messagingSenderId: '379614277244',
    projectId: 'login-d0037',
    authDomain: 'login-d0037.firebaseapp.com',
    storageBucket: 'login-d0037.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCpnGZyOXIl23uc6I5QNJoyPwaEZCsB8',
    appId: '1:379614277244:android:71487bcc95411366ed23f9',
    messagingSenderId: '379614277244',
    projectId: 'login-d0037',
    storageBucket: 'login-d0037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxeJM5ujpymjf1Fu98gsTwxv-VDsqVKE',
    appId: '1:379614277244:ios:6411c15b0a14ec4eed23f9',
    messagingSenderId: '379614277244',
    projectId: 'login-d0037',
    storageBucket: 'login-d0037.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxeJM5ujpymjf1Fu98gsTwxv-VDsqVKE',
    appId: '1:379614277244:ios:4429af7412b7bee2ed23f9',
    messagingSenderId: '379614277244',
    projectId: 'login-d0037',
    storageBucket: 'login-d0037.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
